NAME = btc

SRCS = main.cpp BitcoinExchange.cpp

CLANG = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

RM = rm -rf

all:
	${CLANG}  -g ${SRCS} -o ${NAME}


clean:
	rm -rf ${NAME}

re: clean all

PHOHY: all re clean fclean