NAME = RPN

SRCS = main.cpp

CLANG = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

RM = rm -rf

all:
	${CLANG} ${FLAGS} -g ${SRCS} -o ${NAME}


clean:
	rm -rf ${NAME}

re: clean all

PHOHY: all re clean fclean